### ISSUE TITLE
velocity not defined

### ISSUE THREAD

**Issue by kyas123** [otissv/react-uikit-modal#1]
the button is displayed and on click this error appears. here is my package file -
{
  "name": "react-dash",
  "version": "1.0.0",
  "description": "",
  "main": "components/App.js",
  "scripts": {
    "start": "webpack-dev-server --progress --devtool source-map --port 8080",
    "build": "node_modules/.bin/webpack -p --progress --colors",
    "test": "jest"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "babel-core": "^6.13.2",
    "babel-jest": "^14.1.0",
    "babel-loader": "^6.2.5",
    "babel-plugin-transform-object-rest-spread": "^6.8.0",
    "babel-preset-es2015": "^6.13.2",
    "babel-preset-react": "^6.11.1",
    "install": "^0.8.1",
    "jest": "^14.1.0",
    "memory-fs": "^0.3.0",
    "npm": "^3.10.6",
    "react-test-renderer": "^15.3.0",
    "webpack": "^1.13.2",
    "webpack-dev-server": "^1.14.1"
  },
  "dependencies": {
    "babel-polyfill": "^6.13.0",
    "fixed-data-table": "^0.6.3",
    "flux": "^2.1.1",
    "history": "^1.17.0",
    "install": "^0.8.1",
    "marked": "^0.3.6",
    "npm": "^3.10.6",
    "react": "^15.3.0",
    "react-addons-update": "^15.3.2",
    "react-bootstrap-table": "^2.4.3",
    "react-data-grid": "^1.0.39",
    "react-dom": "^15.3.0",
    "react-redux": "^4.4.5",
    "react-router": "^2.7.0",
    "react-uikit-base": "^2.0.0",
    "react-uikit-form": "^2.0.1",
    "react-uikit-modal": "^2.0.0",
    "react-uikit-table": "^2.0.0",
    "uikit-react": "^0.6.13",
    "velocity-react": "^1.1.11",
    "whatwg-fetch": "^1.0.0"
  }
}

 

this is my error text - EditBP.js:18 Uncaught ReferenceError: velocity is not defined
    at PureFluxContainerClass.animateIn (http://localhost:8080/bundle.js:73429:5)
    at Object._in [as in] (http://localhost:8080/bundle.js:73929:25)
    at show (http://localhost:8080/bundle.js:74244:34)
    at http://localhost:8080/bundle.js:74643:62
    at curried (http://localhost:8080/bundle.js:74588:16)
    at Modal.handleToggleClick (http://localhost:8080/bundle.js:74259:38)
    at Object.ReactErrorUtils.invokeGuardedCallback (http://localhost:8080/bundle.js:6369:17)
    at executeDispatch (http://localhost:8080/bundle.js:6153:22)
    at Object.executeDispatchesInOrder (http://localhost:8080/bundle.js:6176:6)
    at executeDispatchesAndRelease (http://localhost:8080/bundle.js:5598:23)
    at executeDispatchesAndReleaseTopLevel (http://localhost:8080/bundle.js:5609:11)

my whole component-
`import React, {Component} from 'react';
import ReactDOM from 'react-dom';
import {Table, Column, Cell} from 'fixed-data-table';
import {Router, Route, IndexRoute, hashHistory, browserHistory, Link} from 'react-router';
import {Container} from 'flux/utils';
import {BootstrapTable, TableHeaderColumn} from 'react-bootstrap-table';
import BPStore from '../stores/BPStore';
import BPActionCreators from '../actions/BPActionCreators';
import Header from './Header';
import uikit from 'react-uikit-base'
import Modal from 'react-uikit-modal';

class EditBP extends Component {
	animateIn (modal, dialog) {
  this.setState({show: true});
  velocity(modal, {opacity: 1}, {display: 'block'}, 300);
  velocity(dialog, {translateY: 1, opacity: 1}, {display: 'block'}, 200);
}

animateOut (modal, dialog) {
  this.setState({show: false});
  velocity(modal, {opacity:0}, { display: 'none' }, 300);
  velocity(dialog, {translateY: -100, opacity: 0}, { display: 'none' }, 200);
}

	toggleEdit(){
		if (this.state.data.edit === false) {
			BPActionCreators.edit(true);
		} else {
			BPActionCreators.edit(false);
		}
	}

	componentDidMount(){
		//query for table data.
		// if there isnt any BPdata best beleive you retreive it. in this if statement.
			if (this.state.data.selectedBP.CardCode) {
				BPActionCreators.getBPData(this.state.data.selectedBP.CardCode)
			}
	}

	isEquivalent(a, b) {
		// Create arrays of property names
		var aProps = Object.getOwnPropertyNames(a);
		var bProps = Object.getOwnPropertyNames(b);

		// If number of properties is different,
		// objects are not equivalent
		if (aProps.length != bProps.length) {
		   return false;
		}

		for (var i = 0; i < aProps.length; i++) {
		   var propName = aProps[i];

		   // If values of same property are not equal,
		   // objects are not equivalent
		   if (a[propName] !== b[propName]) {
			   return false;
		   }
		}

		// If we made it this far, objects
		// are considered equivalent
		return true;
	}

	save(){
		// checks the value of the store and what is currently on the text fields.
		let bp = this.state.data.selectedBP;
		let currentBP = {
			CardCode: bp.CardCode,
			Email: bp.Email,
			Fax: bp.Fax,
			Name: bp.Name,
			Phone1:bp.Phone1,
			Notes:bp.Notes
		}

		let bpEdit = this.refs
		let newBPObj = {
			CardCode: bp.CardCode,
			Email:bpEdit.newEmail.value,
			Fax: bpEdit.newFax.value,
			Name: bpEdit.newBPName.value,
			Phone1:bpEdit.newPhone1.value,
			Notes:bpEdit.newNotes.value
		}

		BPActionCreators.editBP(newBPObj);
	}

	setBPTable(event){
		BPActionCreators.selectTable(event.target.value);
	}

	render(){
		let table;
		// let selected = this.state.data.selectedTable
		if (this.state.data.selectedTable === 'Contacts' ){
			table = (
				<BootstrapTable data={this.state.data.contacts}search={true}
					striped={true} hover={true} condensed={true}>
					<TableHeaderColumn dataField="Name" >Name</TableHeaderColumn>
					<TableHeaderColumn dataField="Code" isKey={true}>Card Code</TableHeaderColumn>
					<TableHeaderColumn dataField="E-Mail">Email</TableHeaderColumn>
					<TableHeaderColumn dataField="Phone">Phone</TableHeaderColumn>
				</BootstrapTable>
			)
		} else if ( this.state.data.selectedTable === 'Addresses' ) {
			table = (
				<BootstrapTable data={this.state.data.addresses}  search={true}
					striped={true} hover={true} condensed={true} >
					<TableHeaderColumn dataField="AddressType" >Type</TableHeaderColumn>
					<TableHeaderColumn dataField="Type" >Type</TableHeaderColumn>
					<TableHeaderColumn dataField="Address Name" isKey={true}>Name</TableHeaderColumn>
					<TableHeaderColumn dataField="Address Line 1" >Address Line One</TableHeaderColumn>
					<TableHeaderColumn dataField="Address Line 2" >Address Line Two</TableHeaderColumn>
					<TableHeaderColumn dataField="City" >City</TableHeaderColumn>
					<TableHeaderColumn dataField="State" >State</TableHeaderColumn>
					<TableHeaderColumn dataField="Zip" >Zip</TableHeaderColumn>
				</BootstrapTable>
			)
		} else if (this.state.data.selectedTable === 'Invoices') {
			table = (
				<BootstrapTable data={this.state.data.invoices} search={true}
					striped={true} hover={true} condensed={true}>
					<TableHeaderColumn dataField="Description"  >Description</TableHeaderColumn>
					<TableHeaderColumn dataField="Invoice Date" >Invoice Date</TableHeaderColumn>
					<TableHeaderColumn dataField="Invoice Number" isKey={true}>Invoice Number</TableHeaderColumn>
					<TableHeaderColumn dataField="Open Quantity" >Open Quantity</TableHeaderColumn>
					<TableHeaderColumn dataField="Part Number" >Part Number</TableHeaderColumn>
					<TableHeaderColumn dataField="Quantity" >Quantity</TableHeaderColumn>
					<TableHeaderColumn dataField="Row Number" >Row Number</TableHeaderColumn>
					<TableHeaderColumn dataField="Status" >Status</TableHeaderColumn>
					<TableHeaderColumn dataField="Unit Price" >Unit Price</TableHeaderColumn>
				</BootstrapTable>
			)
		} else if ( this.state.data.selectedTable === 'Sales Orders'){
			table = (
				<BootstrapTable data={this.state.data.orders} search={true}
					striped={true} hover={true} condensed={true}>
					<TableHeaderColumn dataField="Contact" >Contact</TableHeaderColumn>
					<TableHeaderColumn dataField="Description" >Description</TableHeaderColumn>
					<TableHeaderColumn dataField="Order Date" >Order Date</TableHeaderColumn>
					<TableHeaderColumn dataField="Row Number">Row Number</TableHeaderColumn>
					<TableHeaderColumn dataField="Part Number">part Number</TableHeaderColumn>
					<TableHeaderColumn dataField="Quantity">Quantity</TableHeaderColumn>
					<TableHeaderColumn dataField="Open Quantity">Open Quantity</TableHeaderColumn>
					<TableHeaderColumn dataField="Unit Price">Unit Price</TableHeaderColumn>
					<TableHeaderColumn dataField="Order Number">Order Number</TableHeaderColumn>
					<TableHeaderColumn dataField="Delivery Date">Delivery Date</TableHeaderColumn>
					<TableHeaderColumn dataField="Tracking Number" isKey={true}>Tracking Number</TableHeaderColumn>
				</BootstrapTable>
			)
		} else if (this.state.data.selectedTable === 'Activities'){
			table = (
				<BootstrapTable data={this.state.data.orders} search={true}
					striped={true} hover={true} condensed={true}>
					<TableHeaderColumn dataField="Activity Number" >Activity Number</TableHeaderColumn>
					<TableHeaderColumn dataField="Activity Date" >Activity Date</TableHeaderColumn>
					<TableHeaderColumn dataField="Activity Time" >Activity Time</TableHeaderColumn>
					<TableHeaderColumn dataField="Contact Person">Contact Person</TableHeaderColumn>
					<TableHeaderColumn dataField="Closed">Closed</TableHeaderColumn>
					<TableHeaderColumn dataField="Contact Number">Contact Number</TableHeaderColumn>
					<TableHeaderColumn dataField="Subject">Subject</TableHeaderColumn>
					<TableHeaderColumn dataField="Content" isKey={true}>Content</TableHeaderColumn>
					<TableHeaderColumn dataField="Assigned To">Assigned To</TableHeaderColumn>
					<TableHeaderColumn dataField="Type">Type</TableHeaderColumn>
					<TableHeaderColumn dataField="Priority" >Priority</TableHeaderColumn>
					<TableHeaderColumn dataField="RelatedDoc" >RelatedDoc</TableHeaderColumn>
					<TableHeaderColumn dataField="RelatedDocType" >RelatedDocType</TableHeaderColumn>
				</BootstrapTable>
			)
		} else if (this.state.data.selectedTable === 'Service Calls'){
			table = (
				<BootstrapTable data={this.state.data.orders} search={true}
					striped={true} hover={true} condensed={true}>
					<TableHeaderColumn dataField="customer" isKey={true}>customer</TableHeaderColumn>
					<TableHeaderColumn dataField="Business Partner Name">Business Partner Name</TableHeaderColumn>
					<TableHeaderColumn dataField="Contact Person">Contact Person</TableHeaderColumn>
					<TableHeaderColumn dataField="Phone #">Phone #</TableHeaderColumn>
					<TableHeaderColumn dataField="Status">Status</TableHeaderColumn>
					<TableHeaderColumn dataField="Priority">Priority</TableHeaderColumn>
					<TableHeaderColumn dataField="RMA#">RMA#</TableHeaderColumn>
					<TableHeaderColumn dataField="Subject">Subject</TableHeaderColumn>
					<TableHeaderColumn dataField="Remarks">Remarks</TableHeaderColumn>
					<TableHeaderColumn dataField="Resolution">Resolution</TableHeaderColumn>
					<TableHeaderColumn dataField="Origin">Origin</TableHeaderColumn>
					<TableHeaderColumn dataField="Service Call Type">Service Call Type</TableHeaderColumn>
					<TableHeaderColumn dataField="Service Type">Service Type</TableHeaderColumn>
					<TableHeaderColumn dataField="State">State</TableHeaderColumn>
				</BootstrapTable>

			)
		} else if (this.state.data.selectedTable ==='Quotes'){
			table = (
				<BootstrapTable data={this.state.data.quotes} search={true}
					striped={true} hover={true} condensed={true}>
					<TableHeaderColumn dataField="Quote Date" isKey={true}>Quote Date</TableHeaderColumn>
					<TableHeaderColumn dataField="Status">Status</TableHeaderColumn>
					<TableHeaderColumn dataField="Row NUmber">Row NUmber</TableHeaderColumn>
					<TableHeaderColumn dataField="Part Number">Part Number</TableHeaderColumn>
					<TableHeaderColumn dataField="Description">Description</TableHeaderColumn>
					<TableHeaderColumn dataField="Quantity">Quantity</TableHeaderColumn>
					<TableHeaderColumn dataField="Open Quantity">Open Quantity</TableHeaderColumn>
					<TableHeaderColumn dataField="Unit Price">Unit Price</TableHeaderColumn>
					<TableHeaderColumn dataField="Contact">Contact</TableHeaderColumn>
					<TableHeaderColumn dataField="Telephone">Telephone</TableHeaderColumn>
					<TableHeaderColumn dataField="Doc Entry">Doc Entry</TableHeaderColumn>
				</BootstrapTable>

			)
		}

		let bp = this.state.data.selectedBP;
		return (
			<div className="bPContainer">
			<Modal
			  close
			  show={this.state.data.edit}
			  trigger={{
				body: 'Open',
				animate: {
				  'in': (modal, dialog) => this.animateIn(modal, dialog),
				  out: (modal, dialog) => this.animateOut(modal, dialog)
				}
			  }}
			>
			  <h2>Headline</h2>
			  <p>
				Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
				tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
				veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex
				ea commodo consequat. Duis aute irure dolor in reprehenderit in
				voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur
				sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt
				mollit anim id est laborum.
			  </p>
			</Modal>

				<h3>Name:<input ref="newBPName" defaultValue={bp.Name} className="uk-form-large uk-form-width-large"></input></h3>
				<h3>Email:<input ref="newEmail" defaultValue={bp.Email} className="uk-form-large uk-form-width-large"></input></h3>
				<h3>Phone:<input ref="newPhone1" defaultValue={bp.Phone1} className="uk-form-large uk-form-width-large"></input></h3>
				<h3>Fax:<input ref="newFax" defaultValue={bp.Fax} className="uk-form-large uk-form-width-large"></input></h3>
				<h3>Notes:<input ref="newNotes" defaultValue={bp.Notes} className="uk-form-large uk-form-width-large"></input></h3>
				<button onClick={this.save.bind(this)}>Save</button>

				<div data-uk-button-radio className="uk-margin-top uk-margin-bottom">
					<button onFocus={this.setBPTable.bind(this)} value="Contacts" className="uk-button">Contacts</button>
					<button onFocus={this.setBPTable.bind(this)} value="Addresses" className="uk-button">Addresses</button>
					<button onFocus={this.setBPTable.bind(this)} value="Quotes" className="uk-button">Quotes</button>
					<button onFocus={this.setBPTable.bind(this)} value="Sales Orders" className="uk-button">Sales Orders</button>
					<button onFocus={this.setBPTable.bind(this)} value="Service Calls" className="uk-button">Service Calls</button>
					<button onFocus={this.setBPTable.bind(this)} value="Invoices"className="uk-button">Invoices</button>
					<button onFocus={this.setBPTable.bind(this)} value="Activities"className="uk-button">Activities</button>
				</div>
				<div>
				{table}
				</div>
			</div>
		);
	}

}

EditBP.getStores = () => ([BPStore]);
EditBP.calculateState = (prevState) => ({
  data: BPStore.getState()
});

export default Container.create(EditBP);`

**Comment by otissv** [comment]
Not actually a react-uikit issue. However, it seems you haven't installed velocity.  npm install --save velocity-animate and  import it into your module.

**Comment by kyas123** [comment]
Thanks alot.
