### ISSUE TITLE
Modal doesn't open if Trigger type is span

### ISSUE THREAD

**Issue by jordan-enev** [otissv/react-uikit-modal#2]
Here are my Modal props
```
<Modal 
close 
show={this.state.show} 
trigger={{
    body: 'Okay',
    type: 'span',
    animate: {
        'in': (modal, dialog)=> this.animateIn(modal, dialog),
        out: (modal, dialog) => this.animateOut(modal, dialog)
    } 
}} >
```

Nothing happens when I click on the span tag.

**Comment by otissv** [comment]
Can you send the full code so I can recreate it?

**Comment by otissv** [comment]
this is due the onClick prop being added to ignore props. I will remove it and it should fix the problem

**Comment by otissv** [comment]
The issues was actually in the trigger component. I've updated both the react-uikit-trigger and the react-uikit-modal. Give it a try and let me know.

**Comment by jordan-enev** [comment]
Tested with `span` type and it works! Thank you! :)
